"use client";
/* eslint-disable @next/next/no-img-element */

import { useState } from "react";

type SubmissionLink = { id?: string; kind: "DEMO" | "VIDEO" | "REPOSITORY" | "SLIDES" | "OTHER"; label: string; url: string };
type SubmissionAsset = { id: string; url: string; caption: string | null; alt_text: string | null };
type Submission = { id: string; title: string; tagline: string; story_markdown: string; links: SubmissionLink[]; assets: SubmissionAsset[] };
const emptyLink: SubmissionLink = { kind: "DEMO", label: "", url: "" };

export function TeamPanel({ teamId, name, members, deadline, submission }: { teamId: string; name: string; members: Array<{ email: string; role: string }>; deadline: string; submission: Submission }) {
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [project, setProject] = useState(submission); const [teamName, setTeamName] = useState(name); const [uploading, setUploading] = useState(false);
  const frozen = new Date(deadline) <= new Date();
  async function saveProject(e: React.FormEvent) { e.preventDefault(); setError(""); const links = project.links.filter((link) => link.label.trim() || link.url.trim()); if (links.some((link) => !link.label.trim() || !link.url.trim())) return setError("Each project link needs both a label and URL."); const r = await fetch(`/api/submissions/${teamId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: project.title, tagline: project.tagline, storyMarkdown: project.story_markdown, links }) }); const d = await r.json() as { error?: string }; if (!r.ok) setError(d.error ?? "Unable to save the project."); else setNotice("Project saved."); }
  async function rename(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/teams", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ teamId, name: teamName }) }); const d = await r.json() as { error?: string }; if (!r.ok) setError(d.error ?? "Unable to rename the team."); else setNotice("Team renamed."); }
  async function uploadImage(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setUploading(true); try { const r = await fetch(`/api/submissions/${teamId}/assets`, { method: "POST", body: new FormData(e.currentTarget) }); const d = await r.json() as { error?: string; asset?: SubmissionAsset }; if (!r.ok || !d.asset) throw new Error(d.error ?? "Unable to upload image."); setProject({ ...project, assets: [...project.assets, d.asset] }); e.currentTarget.reset(); setNotice("Image uploaded."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to upload image."); } finally { setUploading(false); } }
  async function removeImage(assetId: string) { if (!window.confirm("Remove this image?")) return; const r = await fetch(`/api/submissions/${teamId}/assets?assetId=${assetId}`, { method: "DELETE" }); const d = await r.json() as { error?: string }; if (!r.ok) return setError(d.error ?? "Unable to remove image."); setProject({ ...project, assets: project.assets.filter((asset) => asset.id !== assetId) }); }
  const updateLink = (index: number, change: Partial<SubmissionLink>) => setProject({ ...project, links: project.links.map((link, current) => current === index ? { ...link, ...change } : link) });

  return <section className="panel teamPanel"><p className="eyebrow">Your team</p><form onSubmit={rename}><label>Team name<input disabled={frozen} value={teamName} onChange={(event) => setTeamName(event.target.value)} /></label><button className="secondary" disabled={frozen}>Rename team</button></form><p className="mutedCopy">{members.length}/6 members. Your team workspace automatically freezes at {new Date(deadline).toLocaleString()}.</p><h2>Members</h2><ul>{members.map((member) => <li key={member.email}>{member.email} — {member.role}</li>)}</ul>
    {(error || notice) && <p className={error ? "error" : "adminNotice"}>{error || notice}</p>}
    <form onSubmit={saveProject} className="submissionEditor"><div className="submissionEditorHeading"><div><p className="eyebrow">Project submission</p><h2>Tell the story</h2></div><a className="textLink" href={`/submissions/${project.id}`} target="_blank">View project page</a></div><label>Title<input disabled={frozen} value={project.title} onChange={(event) => setProject({ ...project, title: event.target.value })} /></label><label>Tagline<input disabled={frozen} value={project.tagline} onChange={(event) => setProject({ ...project, tagline: event.target.value })} /></label><label>Write-up<textarea disabled={frozen} value={project.story_markdown} onChange={(event) => setProject({ ...project, story_markdown: event.target.value })} placeholder="What did you build? What makes it special?" /></label>
      <div><h3>Project links</h3><p className="mutedCopy">Add your live demo, video, repository, slides, or anything judges should see.</p>{project.links.map((link, index) => <div className="submissionLinkEditor" key={`${link.id ?? "new"}-${index}`}><select disabled={frozen} value={link.kind} onChange={(event) => updateLink(index, { kind: event.target.value as SubmissionLink["kind"] })}><option value="DEMO">Demo</option><option value="VIDEO">Video</option><option value="REPOSITORY">Repository</option><option value="SLIDES">Slides</option><option value="OTHER">Other</option></select><input disabled={frozen} value={link.label} onChange={(event) => updateLink(index, { label: event.target.value })} placeholder="Label" /><input disabled={frozen} value={link.url} onChange={(event) => updateLink(index, { url: event.target.value })} placeholder="https://…" /><button className="linkButton" type="button" disabled={frozen} onClick={() => setProject({ ...project, links: project.links.filter((_, current) => current !== index) })}>Remove</button></div>)}{!frozen && project.links.length < 8 && <button className="secondary" type="button" onClick={() => setProject({ ...project, links: [...project.links, { ...emptyLink }] })}>Add link</button>}</div>{!frozen && <button className="primary">Save project</button>}</form>
    <section className="submissionMedia"><div><p className="eyebrow">Images</p><h2>Show your project</h2><p className="mutedCopy">JPEG, PNG, WebP, or GIF; up to 10 MB each.</p></div>{!frozen && <form onSubmit={uploadImage} className="imageUpload"><label>Image<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required /></label><label>Caption (optional)<input name="caption" maxLength={240} /></label><label>Alt text (optional)<input name="altText" maxLength={240} /></label><button className="secondary" disabled={uploading}>{uploading ? "Uploading…" : "Upload image"}</button></form>}<div className="submissionGallery">{project.assets.map((asset) => <figure key={asset.id}><img src={asset.url} alt={asset.alt_text ?? asset.caption ?? "Project image"} /><figcaption>{asset.caption}</figcaption>{!frozen && <button className="linkButton" onClick={() => void removeImage(asset.id)}>Remove image</button>}</figure>)}</div></section>
  </section>;
}
